#!/bin/sh

echo "The shellscript for modifying of network settings."



echo -n "Input ip addr to set："
read ipaddr

echo -n "Input mac addr to set："
read macaddr

sed -i -e "s/^IPADDR$/IPADDR=$ipaddr/" /etc/sysconfig/network-scripts/ifcfg-eth0 
sed -i -e "s/^HWADDR$/HWADDR=$macaddr/" /etc/sysconfig/network-scripts/ifcfg-eth0 

#perl -pe "s/# net device ()\nSUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"00:15:5d:0b:c8:04\", ATTR{type}==\"1\", KERNEL==\"eth*\", NAME=\"eth0\"//g" /etc/udev/rules.d/70-persistent-net.rules
#perl -pe "s/eth1/eth0/g" /etc/udev/rules.d/70-persistent-net.rules

lines="# This file was automatically generated by the /lib/udev/write_net_rules\n# program, run by the persistent-net-generator.rules rules file.\n#\n# You can modify it, as long as you keep each rule on a single\n# line, and change only the value of the NAME= key.\n\n# net device () \nSUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"$macaddr\", ATTR{type}==\"1\", KERNEL==\"eth*\", NAME=\"eth0\"\n"
echo $lines > /etc/udev/rules.d/70-persistent-net.rules

echo "Completed! Reboot in 10 seconds!\n"
sleep 10

reboot
